parameters:
  oro.activity_list.event_listener.actitity_list_listener.class: Oro\Bundle\ActivityListBundle\EventListener\ActivityListListener
  oro.activity_list.provider.chain.class: Oro\Bundle\ActivityListBundle\Provider\ActivityListChainProvider
  oro.activity_list.manager.class: Oro\Bundle\ActivityListBundle\Manager\ActivityListManager
  oro.activity_list.entity_config_dumper.extension.class: Oro\Bundle\ActivityListBundle\Tools\ActivityListEntityConfigDumperExtension
  oro.activity_list.entity_generator.extension.class: Oro\Bundle\ActivityListBundle\Tools\ActivityListEntityGeneratorExtension

services:
  oro.activity_list.event_listener.actitity_list_listener:
      class:  %oro.activity_list.event_listener.actitity_list_listener.class%
      arguments:
          - @oro.activity_list.manager
          - @oro_entity.doctrine_helper
      tags:
          - { name: doctrine.event_listener, event: onFlush }
          - { name: doctrine.event_listener, event: postFlush }

  oro.activity_list.provider.chain:
      class: %oro.activity_list.provider.chain.class%
      arguments:
         - @oro_security.security_facade.link
         - @oro_entity.doctrine_helper

  oro.activity_list.manager:
      class: %oro.activity_list.manager.class%
      arguments:
         - @oro.activity_list.provider.chain

  oro.activity_list.entity_config_dumper.extension:
      class: %oro.activity_list.entity_config_dumper.extension.class%
      arguments:
          - @oro.activity_list.provider.chain
          - @oro_entity_config.config_manager
          - @oro_entity_extend.association_builder
      tags:
          - { name: oro_entity_extend.entity_config_dumper_extension }

  oro.activity_list.entity_generator.extension:
          class: %oro.activity_list.entity_generator.extension.class%
          arguments:
              - @oro.activity_list.provider.chain
          tags:
              - { name: oro_entity_extend.entity_generator_extension }