parameters:
  oro.activity_list.event_listener.actitity_list_listener.class: Oro\Bundle\ActivityListBundle\EventListener\ActivityListListener

services:
  oro.activity_list.event_listener.actitity_list_listener:
      class:  %oro.activity_list.event_listener.actitity_list_listener.class%
      arguments:
          - @oro_entity.doctrine_helper
      tags:
          - { name: doctrine.event_listener, event: onFlush }
          - { name: doctrine.event_listener, event: postFlush }
