oro_system_configuration:
    groups:
        activity_list_settings:
            title:  oro.activitylist.system_configuration.activity_list.label

    fields:
        oro_activity_list.sorting_field:
            data_type: string
            type: choice
            options:
                label: oro.activitylist.system_configuration.fields.sorting_field.label
                choices:
                    createdAt: oro.activitylist.system_configuration.fields.sorting_field.choices.createdAt
                    updatedAt: oro.activitylist.system_configuration.fields.sorting_field.choices.updatedAt
                constraints:
                    - NotBlank: ~
        oro_activity_list.sorting_direction:
            data_type: string
            type: choice
            options:
                label: oro.activitylist.system_configuration.fields.sorting_direction.label
                choices:
                    DESC: oro.activitylist.system_configuration.fields.sorting_direction.choices.DESC
                    ASC: oro.activitylist.system_configuration.fields.sorting_direction.choices.ASC
                constraints:
                    - NotBlank: ~
        oro_activity_list.per_page:
            data_type: integer
            type: choice
            options:
                label: oro.activitylist.system_configuration.fields.per_page.label
                #tooltip: oro.activitylist.system_configuration.fields.per_page.tooltip
                choices:
                    1: 1
                    2: 2
                    3: 3
                    5: 5
                    10:     10
                    25:     25
                    50:     50
                    100:    100
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    activity_list_settings:
                                        children:
                                            - oro_activity_list.sorting_field
                                            - oro_activity_list.sorting_direction
                                            - oro_activity_list.per_page

    api_tree:
        activity_list:
            oro_activity_list.sorting_field: ~
            oro_activity_list.sorting_direction: ~
            oro_activity_list.per_page: ~
